name: Branch Naming Convention
on:
  push:
    branches-ignore:
      - main
      - develop
      - staging
  create:

jobs:
  check-branch-name:
    runs-on: ubuntu-latest
    steps:
      - name: Check branch name
        uses: actions/github-script@v7
        with:
          script: |
            const branchName = context.ref.replace('refs/heads/', '');
            
            // Skip if it's a tag creation
            if (context.ref.startsWith('refs/tags/')) {
              console.log('Tag creation detected, skipping branch validation');
              return;
            }
            
            const allowedPatterns = [
              /^feature\/.+/,
              /^release\/.+/,
              /^hotfix\/.+/,
              /^bugfix\/.+/,
              /^(main|develop|staging)$/
            ];
            
            const isValid = allowedPatterns.some(pattern => pattern.test(branchName));
            
            if (!isValid) {
              const message = `❌ Branch name "${branchName}" does not follow naming conventions.
              
              Allowed patterns:
              • feature/* - New feature development
              • release/* - Release preparation and final testing
              • hotfix/* - Critical production fixes
              • bugfix/* - Non-critical bug fixes
              
              Examples:
              • feature/user-authentication
              • bugfix/login-validation
              • hotfix/security-patch
              • release/v1.2.0`;
              
              throw new Error(message);
            }
            
            console.log(`✅ Branch name "${branchName}" is valid`);